# Generated by Django 3.2.5 on 2021-09-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_platform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchList',
            new_name='MovieList',
        ),
    ]
