# Generated by Django 3.2.5 on 2021-09-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_rename_watchlist_movielist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieList',
            new_name='WatchList',
        ),
    ]
