# Generated by Django 3.2.5 on 2021-10-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movielist', to='watchlist_app.streamplatform'),
        ),
    ]
